### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by adroition** [TotalCore/MusicBot#5]
Savnith - Today at 7:21 PM
what?
;play Psycho kid flees contry
Music PugBOT - Today at 7:22 PM
Enqueued Psycho Kid Flees Country to be played. Position in queue: Up next!
@Savnith - your song Psycho Kid Flees Country is now playing in General you slut!
Legendaria - Today at 7:22 PM
;queue
Music PugBOT - Today at 7:22 PM
Now Playing: Psycho Kid Flees Country added by Savnith [00:02/14:39]

This user has no rank.
The time limit NEEDS to be changed.

**Comment by rovertdude** [comment]
approved, all times should be lowered

**Comment by foxcqrn** [comment]
@rovertdude I suggest you lower them to 5 minutes or something.

**Comment by rovertdude** [comment]
@FoxIshDaBest It is set to 5 minutes.

**Comment by foxcqrn** [comment]
Alright
