### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by adroition** [TotalCore/MusicBot#9]
[Command] 188094959306407937/Nik0las (;play piccolos best tfs)
<class 'musicbot.exceptions.PermissionsError'>: You don't have permission to use that command.
Reason: Song duration exceeds limit (843 > 500)
This user is supposed to have global moderator access, and therefore would have a higher time limit and would be able to play this.

**Comment by rovertdude** [comment]
He isn't in the Management group.
Are you sure of this?

**Comment by adroition** [comment]
It's possible you removed him from the permissions file.

**Comment by adroition** [comment]
Confirmed again - my bad - he is in the group and he is a Global Admin

**Comment by rovertdude** [comment]
this could be something with the permissions.ini
